### ISSUE TITLE
Rapid Fire

### ISSUE THREAD

**Issue by HadAField** [RocketGod-git/Flipper-Zero-Laser-Tag#7]
Flipper will not stop vibrating if shot from someone who was holding down the fire button.
Vibrated for over 30 seconds; Had to restart the Flipper to get it to stop vibrating.

**Comment by RocketGod-git** [comment]
Thanks for letting me know! I'll fix this asap.

**Comment by RocketGod-git** [comment]
Bug should be fixed. Please update your app and let me know if you find anything else. 😎🤘
Thanks @jamisonderek for the quicky.
